### ISSUE TITLE
 Contributing.MD and  CODE_OF_CONDUCT.md are almost the same 

### ISSUE THREAD

**Issue by komalswami** [tintindas/ynwa-emailer#2]
Contributing.MD and  CODE_OF_CONDUCT.md are almost the same so can be separated.

**Comment by tintindas** [comment]
Oops! Seems like I copied in the wrong template. Thanks for pointing it out. I will fix it ASAP.

If you have any suggestions for what would help you contribute to this project more easily please feel free to make edits to the CONTRIBUTING.md file and raise a PR.

**Comment by tintindas** [comment]
PR #4 updates the docs and improves the CONTRIBUTIONS.md file for an easier developer experience.
