### ISSUE TITLE
add | debargho.basak1999@gmail.com

### ISSUE THREAD

**Issue by Debargho99** [tintindas/ynwa-emailer#3]
Add me to the mailing list

**Comment by Debargho99** [comment]
debargho.basak1999@gmail.com

**Comment by tintindas** [comment]
Added you to the mailing list.

**Screenshot**
![image](https://user-images.githubusercontent.com/47525983/116775309-04eb5700-aa80-11eb-99d5-d74ff0bba04e.png)

Please check spam folder if mail not in inbox.
